#!/bin/bash

set -e
set -o pipefail

########################################################################
# Load modules
module load python/3.9.9
module load R/4.4.0

########################################################################
# Set up running directory
cd "$(dirname "${BASH_SOURCE[0]}")" 

# Read root path
rootdir=$(realpath "./../..")
echo "$rootdir"

########################################################################
# Read multiple values and assign them to variables by parsing yaml file
cellranger_parameters=$(cat ${rootdir}/project_parameters.Config.yaml | grep 'cellranger_parameters:' | awk '{print $2}')
cellranger_parameters=${cellranger_parameters//\"/}  # Removes all double quotes
echo "$cellranger_parameters"  # Output: This is a string with quotes.

genome_name_cellranger=$(cat ${rootdir}/project_parameters.Config.yaml | grep 'genome_name_cellranger:' | awk '{print $2}')
genome_name_cellranger=${genome_name_cellranger//\"/}  # Removes all double quotes
echo "$genome_name_cellranger"  # Output: This is a string with quotes.

########################################################################
# Create directories to save output files to
mkdir -p ./results/03_cellranger_count_summary
mkdir -p ./results/03_cellranger_count_summary/${cellranger_parameters}
mkdir -p ./results/03_cellranger_count_summary/${cellranger_parameters}/multi_run_${cellranger_parameters}

echo "./results/03_cellranger_count_summary/${cellranger_parameters}/multi_run_${cellranger_parameters}"

module_dir="${rootdir}/analyses/cellranger-analysis"
results_dir="${module_dir}/results"

##################################################################################################
# Step 1 #########################################################################################
# We need to transform the CSV file for each sample to match the one from cellranger count
Rscript --vanilla j2-prepare-CSV.R


##################################################################################################
# Step 2 #########################################################################################
# Run to summarize results generated by CellRanger for all libraries
python ./util/summarize_cellranger_results.py --dir=./results/02_cellranger_count/${cellranger_parameters}/multi_run_${cellranger_parameters}/outs/per_sample_outs \
                                              --outdir=./results/03_cellranger_count_summary/${cellranger_parameters}/multi_run_${cellranger_parameters}/


                                              